# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-26 23:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FailedAttemptLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('phone_hash', models.CharField(db_index=True, max_length=1024)),
                ('failure', models.PositiveSmallIntegerField(choices=[(1, 'bad phone/password match'), (2, 'bad vote code')])),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('title', models.TextField()),
                ('shortcode', models.CharField(max_length=10)),
                ('status', models.SmallIntegerField(default=0)),
                ('district', models.ManyToManyField(db_index=True, to='phonedemocracy.District')),
            ],
        ),
        migrations.CreateModel(
            name='IssueVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_hash', models.CharField(db_index=True, max_length=1024)),
                ('procon', models.SmallIntegerField()),
                ('shouldvote', models.SmallIntegerField()),
                ('validation_code', models.TextField()),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phonedemocracy.Issue')),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_name_pw_hash', models.CharField(db_index=True, max_length=1024)),
                ('webpw_hash', models.CharField(db_index=True, max_length=1024)),
                ('index', models.IntegerField(default=0)),
                ('phone_pw_hash', models.CharField(db_index=True, max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='VoterChangeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('phone_hash', models.CharField(db_index=True, max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='VoterUnique',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_address_hash', models.TextField()),
            ],
        ),
    ]
