# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-06 19:09
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('phonedemocracy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvalidToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invalidation_token_hash', models.CharField(max_length=1024)),
            ],
        ),
        migrations.RemoveField(
            model_name='voter',
            name='index',
        ),
        migrations.AddField(
            model_name='voter',
            name='invalidation_token',
            field=models.CharField(db_index=True, default='xxx', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voterunique',
            name='invalidation_token_hash',
            field=models.CharField(default='xxx', max_length=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='failedattemptlog',
            name='failure',
            field=models.PositiveSmallIntegerField(choices=[(1, 'bad phone/password match'), (2, 'bad vote decode (bad iv or other assertion error)'), (3, 'bad vote code (no issue)')]),
        ),
    ]
